rpm/el8
edf-hpc/hpcstats pull request #13
Opened 2021-03-26 10:28 UTC by nilce05

2021-03-26 15:46 UTC, granquet requested changes

2021-03-26 15:46 UTC, granquet commented on hpcstats.spec
> +%config %{_datadir}/%{name}/bin/jobstats
I'm not sure the "binaries" should be declared as %config

this comment applies throughout the whole file.

2021-03-26 15:46 UTC, granquet commented on hpcstats.spec
> +%config %{_datadir}/%{name}/bin/sync-hpcstats-slurm-job-accounts
I see 3 scripts in the %description but only two scripts in the %files ?

2021-03-26 15:46 UTC, granquet commented on hpcstats.spec
> +%{python3_sitelib}
can you be a bit more specific? ie: %{python3_sitelib}/%{name} ?

2021-03-29 13:26 UTC, nilce05 commented on hpcstats.spec
> +%config %{_datadir}/%{name}/bin/jobstats
totally agree with you, it’s my mistake, I take it for myself and I correct it
```
-%config %{_datadir}/%{name}/bin/jobstats.tpl.sh
-%config %{_datadir}/%{name}/bin/jobstats
+%{_datadir}/%{name}/bin/jobstats.tpl.sh
+%{_datadir}/%{name}/bin/jobstats
.....
-%config %{_datadir}/%{name}/bin/launch-jobstats
+%{_datadir}/%{name}/bin/launch-jobstats
.....
-%config %{_datadir}/%{name}/bin/fsusage
+%{_datadir}/%{name}/bin/fsusage
.....
-%config %{_datadir}/%{name}/bin/encode-password
-%config %{_datadir}/%{name}/bin/sync-hpcstats-slurm-job-accounts
+%{_datadir}/%{name}/bin/encode-password
+%{_datadir}/%{name}/bin/sync-hpcstats-slurm-job-accounts
```

2021-03-29 14:25 UTC, nilce05 commented on hpcstats.spec
> +%config %{_datadir}/%{name}/bin/sync-hpcstats-slurm-job-accounts
That’s a very good point.
From what I understand, the scripts in the %description section are mainly managed by the main program HPCStatsImporter. 
What is described in the %files section does' nt necessarily reflect all scripts of the %description as in the case of the encode-password

2021-03-29 14:27 UTC, nilce05 commented on hpcstats.spec
> +%{python3_sitelib}
like this ??? : 
```
-%{python3_sitelib}
+%{python3_sitelib}/HPCStats/*
+%{python3_sitelib}/*%{name}*.egg-info
```

2021-04-01 04:04 UTC, granquet commented on hpcstats.spec
> +%config %{_datadir}/%{name}/bin/sync-hpcstats-slurm-job-accounts
The description and the content should match.
else it doesn't make sense?

2021-04-01 04:09 UTC, granquet requested changes

2021-04-01 04:09 UTC, granquet commented on hpcstats.spec
> +%config %{_bindir}/hpcstats
%{_bindir} as %config seems dubious to me?

2021-04-01 04:09 UTC, granquet commented on hpcstats.spec
> +install -d %{buildroot}/%{_datadir}/%{name}/db
general "style" comment (that is not worth fixing overall imho):
choose if you want to append a / between the folder variables or not.
ie: %{buildroot}__/__%{_datadir} or %{buildroot}%{_datadir}

2025-10-15 14:26 UTC, closed without merging